#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);
use File::Path;

# Group ownership is changed to admin group, 
# if the ibay group owner is deleted:
event_actions('group-delete', 
	     "nethserver-ibays-reset-group" => "10"
    );

# create
event_actions('ibay-create', qw(
	     nethserver-ibays-ibay-create 15
	     nethserver-ibays-set-permissions 20
));

# modify
event_actions('ibay-modify', qw(
	     nethserver-ibays-set-permissions 20
));

# delete
event_actions('ibay-delete', 
	     'nethserver-ibays-ibay-delete' => '15'
    );

# package install/update
event_actions('nethserver-ibays-update',
	     'initialize-default-databases' => '00',
	     'nethserver-ibays-conf' => '30'
    );

# user create: add to "shared" group
event_actions('user-create',
	      'nethserver-ibays-user-create' => '30');

#--------------------------------------------------
# actions for ibay-name validator
#--------------------------------------------------
validator_actions('ibay-create', qw(
                  uniq-account 20
                  ibay-length 30
));

validator_actions('ibay-delete', qw(
                  ibay-removable 20
));


