#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

# Group ownership is changed to admin group, 
# if the ibay group owner is deleted:
event_action('group-delete', 
	     "nethserver-ibays-reset-group" => "10"
    );

# create
event_action('ibay-create', 
	     "nethserver-ibays-ibay-create" => "15",
	     "nethserver-ibays-set-permissions" => "20"
    );

# modify
event_action('ibay-modify', 
	     "nethserver-ibays-ibay-modify" => "15",
	     "nethserver-ibays-set-permissions" => "20"
    );

# delete
event_action('ibay-delete', 
	     'nethserver-ibays-ibay-delete' => '15'
    );

# package install/update
event_action('nethserver-ibays-update'
	     'initialize-default-databases' => '00',
	     'nethserver-ibays-conf' => '30'
    );

#--------------------------------------------------
# actions for ibay-name validator
#--------------------------------------------------
my $validator = 'ibay-name';
validator_link("uniq-account", $validator, 20);
validator_link("ibay-length", $validator, 30);
