#!/usr/bin/perl

#
# NethServer Ibays
#
# Add the newly created unix user to "shared" group
#
# The new user name is specified by the second argument to the script.
# If the user name value has not been set ALL users in AccountDB are processed.
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::AccountsDB;

my $event = shift;
my $user = shift;
my @users = ();
my $accountsDb = esmith::AccountsDB->open_ro();

my $errors = 0;

my $lgroupmod = '/usr/sbin/lgroupmod';

if($user) {
    if($accountsDb->get_prop($user, 'type') ne 'user') {
	die("Invalid user account name: `$user`");
    }
    @users = ($user);
} else {
    @users = map { $_->key } $accountsDb->users();   
}


foreach my $user (@users) {
    if(system($lgroupmod, '-M', $user, 'shared') != 0) {
	$errors ++;
	warn "Failed to add `$user` in group `shared`\n";
    }
}

exit($errors == 0 ? 0 : 1);
