#!/usr/bin/perl -w

use strict;
use esmith::AccountsDB;
use esmith::event;

my $errors = 0;

#
# This action is executed on group deletion
#

my $accounts = esmith::AccountsDB->open() or 
    die "Unable to open accounts db: $!";

my ($eventName, $deleted_group) = @ARGV;

# Find all "i-bay" entries in the e-smith accounts database and
# if the group matches this one, change it to group "admin".
 
my @modified_ibays;

foreach my $ibay ( $accounts->ibays ) {
    if ( $ibay->prop('Group') eq $deleted_group ) {
	$ibay->set_prop( 'Group', 'admin' );
	push @modified_ibays, $ibay->key;
	if( ! event_signal('ibay-modify', $ibay->key) ) {
	    $errors ++;
	}
    }
}

exit($errors > 0 ? 1 : 0);
