#!/usr/bin/perl

use strict;

#
# NethServer - nethserver-ibays-conf
#
# Copyright (C) 2012 Nethesis srl
#

use esmith::AccountsDB;
use esmith::event;

my $errors = 0;
my $accountsDb = esmith::AccountsDB->open_ro() or die("Fatal error opening accounts DB\n");
my $lgroupadd = '/usr/sbin/lgroupadd';
my $lgroupmod = '/usr/sbin/lgroupmod';
my $ibayBasePath = '/var/lib/nethserver/ibay/';

#
# Create shared group if not exists
#
my $gid = getgrnam('shared');

if( ! $gid) {
    system($lgroupadd, 'shared');
}

my @users = map { $_->key } $accountsDb->users();

#
# Assign admin and all known users to shared group:
#
system($lgroupmod, '-M', join(',', 'admin', @users), 'shared');

if($? != 0) {
    $errors ++;
}

#
# Create ibay if db record is present but directory is missing:
#
foreach my $ibay ($accountsDb->ibays()) {
    my $ibayName = $ibay->key();
    if ( -d $ibayBasePath . $ibayName ) {
	next;
    }

    if(event_signal('ibay-create', $ibayName) == 0) {
	$errors ++;
    }
}

exit($errors > 0 ? 1 : 0);
