#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::AccountsDB;
use NethServer::Migrate qw(migrateDir);
use esmith::event;

my $event = shift;
my $sourceDir = shift;
my $esmithDbDir = '/home/e-smith/db';
my $errors = 0;

if( ! $event ) {
    die("Missing event argument!\n");
}

if( ! $sourceDir ) {
    die("Missing sourceDir argument!\n");
}

my $accountsDb = esmith::AccountsDB->open('accounts') or die("Could not open accounts db\n");

foreach my $ibay ($accountsDb->ibays()) {
    my $ibayName = $ibay->key;
    my $isCreated = defined $ibay->prop('__new') ;

    my $eventName = $isCreated ? 'ibay-create' : 'ibay-modify';
    if( ! esmith::event::event_signal($eventName, $ibayName)) {
	warn("[ERROR] $eventName $ibayName event failed\n");
	$errors++;
	next;
    }

    if($isCreated) {
	$ibay->delete_prop('__new');
    }

    # Skip data migration,  if destination exists:
    if( -d  '/var/lib/nethserver/ibay/' . $ibayName) {
	warn "[WARNING] $ibayName: ibay directory exists. Data migration skipped.\n";
	next;
    }

    # Migrate data
    if( ! migrateDir(
	      $sourceDir . '/home/e-smith/files/ibays/' . $ibayName, 
	      '/var/lib/nethserver/ibay/' . $ibayName
	)) {
	    warn("[ERROR] failed to migrate $ibayName ibay directory.\n");
	    $errors++;
	    next;
    }
    
    if( ! esmith::event::event_signal('ibay-reset-permissions', $ibayName)) {
	warn("[ERROR] ibay-reset-permissions $ibayName event failed\n");
	$errors++;
	next;
    }
	
}

# Restore ACLs
chdir '/var/lib/nethserver/ibay/';
system('/usr/bin/setfacl', '--restore=' . $sourceDir . '/home/e-smith/db/acls.dump');
if($? != 0) {
    warn("[ERROR] failed to restore POSIX ACLs\n");
    $errors++;
}


if($errors > 0) {
    warn "[WARNING] $errors error(s) occurred in $0 action\n";
    exit(1);
}

# action ends:
exit(0);
