#!/usr/bin/perl 

#
# nethserver-ibays-set-password -- change the ibay password with htpasswd
#
# Copyright (C) 2012 Nethesis srl
#

use strict;

use esmith::AccountsDB;

my $eventName = shift || die('Missing event name argument!');
my $ibayName = shift || die('Missing ibay name argument!');

my $passwordFile = '/etc/httpd/conf/ibays.htpasswd';
my $htpasswd = '/usr/bin/htpasswd';

my $db = esmith::AccountsDB->open_ro() || die('Could not open accounts database!');

if($db->get_prop($ibayName, 'type') ne 'ibay') {
    die("The given argument \"$ibayName\" is not an ibay account!");
}

if($db->get_prop($ibayName, 'HttpPasswordStatus') ne 'enabled') {
    exit 0;
}

my $password = $db->get_prop($ibayName, 'HttpPasswordValue');

if($password) {
    my $action = (-r $passwordFile ? 'update' : 'create');
    if(system($htpasswd, 
	      '-bs' . ($action eq 'create' ? 'c' : ''), 
	      $passwordFile, 
	      $ibayName, 
	      $password) != 0) {
	die("Could not $action the htpasswd database file in " . $passwordFile);
    }
} else {
    die "Password has not been set in HttpPasswordValue, for ibay $ibayName\n";
}

