#!/usr/bin/perl

#
# NethServer Ibays
#
# Add the newly created unix user to "shared" group
#
# The new user name is specified by the second argument to the script.
# If the user name value has not been set ALL users in AccountDB are processed.
#
# @copyright (C) 2012 Nethesis srl
#

use strict;
use esmith::AccountsDB;

my $event = shift;
my $user = shift;
my @users = ();
my $accountsDb = esmith::AccountsDB->open_ro();

my $errors = 0;

my $lgroupmod = '/usr/sbin/lgroupmod';

if($user) {
    if($accountsDb->get_prop($user, 'type') ne 'user') {
	die("Invalid user account name: `$user`");
    }
    @users = ($user);
} else {
    @users = map { $_->key } $accountsDb->users();   
}


foreach my $user (@users) {
    if(system($lgroupmod, '-M', $user, 'shared') != 0) {
	$errors ++;
	warn "Failed to add `$user` in group `shared`\n";
    }
}

exit($errors == 0 ? 0 : 1);
