#!/usr/bin/perl -w

#----------------------------------------------------------------------
# copyright (C) 1999-2005 Mitel Networks Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#
#----------------------------------------------------------------------
package esmith;

use strict;
use Errno;
use esmith::util;
use esmith::templates;
use esmith::AccountsDB;


$ENV{'PATH'} = "/bin";

my $event = $ARGV [0];
my $ibayName = $ARGV [1];

die "ibayName argument missing" unless defined ($ibayName);

my $accountdb = esmith::AccountsDB->open();
my $ibay = $accountdb->get($ibayName) or 
	die "Couldn't find $ibayName record in accounts db\n";

if ($ibay->prop('type') ne 'ibay') {
    die "Account $ibayName is not an ibay account; create ibay event failed.\n"
}


#------------------------------------------------------------
# Create the Unix user and group accounts
#------------------------------------------------------------

# Create the ibay's unique group first

my $uid  = $accountdb->get_next_uid();

system(
    "/usr/sbin/lgroupadd",
    "-g",
    $uid,
    $ibayName
) == 0 or die "Failed to create group $ibayName.\n";

system(
    "/usr/sbin/luseradd",
    "-u",
    $uid,
    "-g",
    $uid,
    "-c",
    $ibay->prop("Name"),
    "-d",
    "/home/e-smith/files/ibays/$ibayName/files",
    "-M",
    "-s",
    "/bin/false",
    $ibayName
) == 0 or die "Failed to create account $ibayName.\n";

system("/usr/sbin/lusermod", "-L", $ibayName) == 0
    or warn "Error locking account $ibayName";

$accountdb->set_prop($ibayName,"Uid",$uid);
$accountdb->set_prop($ibayName,"Gid",$uid);

system("/usr/sbin/lgroupmod", "-M", $ibayName, 'shared') == 0
    or die "Failed to add $ibayName into group shared.\n";

system("/usr/sbin/lgroupmod", "-M", $ibayName, $ibay->prop("Group")) == 0
    or die "Failed to add $ibayName into group ".$ibay->prop("Group").".\n";

system("/bin/cp", "-Rp", "/etc/e-smith/skel/ibay",
    "/home/e-smith/files/ibays/$ibayName") == 0
	or die "Error copying ibay skeletal files";

processTemplate({
    TEMPLATE_PATH => "/home/e-smith/files/ibays/html/index.html",
    OUTPUT_FILENAME => "/home/e-smith/files/ibays/$ibayName/html/index.html",
    MORE_DATA => { IBAY_NAME => $ibayName },
		});

