#!/usr/bin/perl -w

#----------------------------------------------------------------------
# copyright (C) 1999-2005 Mitel Networks Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#
#----------------------------------------------------------------------
package esmith;

use strict;
use Errno;
use File::Find;
use esmith::util;
use esmith::AccountsDB;

my $ibayBasePath = '/var/lib/nethserver/ibay/';

my $event = shift;
my $ibayName = shift;

die "ibayName argument missing" unless defined ($ibayName);

my $accountdb = esmith::AccountsDB->open();
my $ibay = $accountdb->get($ibayName) or 
	die "Couldn't find $ibayName record in accounts db\n";

if ($ibay->prop('type') ne 'ibay') {
    die "Account $ibayName is not an ibay account; modify ibay event failed.\n"
}

my $ibayPath = $ibayBasePath . $ibayName;

my $OwningGroup = $ibay->prop('OwningGroup') ?  $ibay->prop('OwningGroup') : 'root';
my $GroupAccess = $ibay->prop('GroupAccess') ?  $ibay->prop('GroupAccess') : 'rw';
my $OtherAccess = $ibay->prop('OtherAccess') ?  $ibay->prop('OtherAccess') : '';


my $basePerms = 0600;

if($GroupAccess =~ /r/) {
    $basePerms |= 040;
}

if($GroupAccess =~ /w/) {
    $basePerms |= 020;
}

if($OtherAccess =~ /r/) {
    $basePerms |= 04;
}

sub process
{
    if (-l) {
	$File::Find::prune = 1;
	return;
    }

    esmith::util::chownFile('root', $OwningGroup, $_);

    my $perms = $basePerms;
       
    if (-d) {
	# Set execute and set-gid bits on directories:
	$perms |= $basePerms & 040 ? 02010 : 0; # is readable by group?
	$perms |= $basePerms & 004 ? 1 : 0; # is readable by others?
	$perms |= 0100; # always readable by owner (root)
    } elsif (-f) {
	# Preserve execute permissions on files:
	$perms |= (stat($_))[2] & 0111;
    } else {
	# Skip other file types..
	return;
    }  
    
    # printf "chmod %o %s\n", $perms, $_;
    chmod $perms, $_;
}

chdir $ibayPath;
find(\&process, $ibayPath);

