#!/bin/sh

#----------------------------------------------------------------------
# copyright (C) 1999-2005 Mitel Networks Corporation
#		
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#		
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#		
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
# 
#----------------------------------------------------------------------

#------------------------------------------------------------
# Delete the Unix account and files for the ibay.
#------------------------------------------------------------

event=$1
ibay=$2

if [ -z "$ibay" ]; then
    echo ibay name argument missing
    exit 1
fi

/bin/rm -rf "/var/lib/nethserver/ibay/${ibay:-xxx}"

