#!/usr/bin/perl

use strict;

#
# NethServer - nethserver-ibays-conf
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::AccountsDB;
use esmith::event;

my $errors = 0;
my $accountsDb = esmith::AccountsDB->open_ro() or die("Fatal error opening accounts DB\n");
my $ibayBasePath = '/var/lib/nethserver/ibay/';

#
# Create ibay if db record is present but directory is missing:
#
foreach my $ibay ($accountsDb->ibays()) {
    my $ibayName = $ibay->key();
    if ( -d $ibayBasePath . $ibayName ) {
	next;
    }

    if(event_signal('ibay-create', $ibayName) == 0) {
	$errors ++;
    }
}

exit($errors > 0 ? 1 : 0);
