#!/usr/bin/perl -w

use strict;
use esmith::AccountsDB;

=head2 ibay-removable

Exit code 4, if ibay is not removable

0 on SUCCESS

=cut

my $ibayName = shift || die("Missing ibay name argument");
my $db = esmith::AccountsDB->open_ro() or die("Could not open AccountsDB");
    
my $removable = $db->get_prop($ibayName, 'Removable');

if( defined $removable && $removable eq 'no')  {
    printf "Ibay `%s` is not removable\n", $ibayName;
    exit 4;
}

exit 0;

