#!/usr/bin/perl -w
package esmith;

use esmith::ConfigDB;

=head2 validate_account_length ACCOUNTNAME

returns 'OK' if the account name is shorter than the maximum account name length
returns 'ACCOUNT_TOO_LONG' otherwise

=cut

my $ibayName = shift;
exit 1 unless ($ibayName ne "");

my $db = esmith::ConfigDB->open_ro() or exit 1;
    

my $maxIbayNameLength = ($db->get('maxIbayNameLength')
   ? $db->get('maxIbayNameLength')->prop('type')
   : "") || 32;

if ( length $ibayName > $maxIbayNameLength ) {
    print "'$ibayName' is too long. Max length is: $maxIbayNameLength\n"; 
    exit 1 
} else {
    exit 0;
}
