#!/usr/bin/perl -w

use esmith::ConfigDB;

=head2 ibay removable



=cut

my $ibayName = shift || die("Missing ibay name argument");
my $db = esmith::AccountsDB->open_ro() or die("Could not open AccountsDB");
    
my $removable = $db->get_prop($ibayName, 'Removable');

if( defined $removable && $removable eq 'no')  {
    printf "Ibay `%s` is not removable\n", $ibayName;
    exit 4;
}

exit 0;

